"""
Django settings for sistema_vendas_auto project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2n0pwdzfyo#e3_a)1(%!z*jnu^6gi^gjezf!xdm*-ow*96&ai8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'carros.apps.CarrosConfig',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_vendas_auto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_vendas_auto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'carros.validators.SenhaSuperForteValidator',
    },
]

# Diz ao Django para tentar fazer login usando o ficheiro personalizado primeiro
AUTHENTICATION_BACKENDS = [
    'carros.backends.EmailLoginBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Django usar os pontos nos milhares (150.000,00)
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Para onde ir após fazer login com sucesso (apontar para a raiz do site)
LOGIN_REDIRECT_URL = '/'

# Para onde ir após sair (logout) - Redireciona de volta para a tela de login
LOGOUT_REDIRECT_URL = '/contas/login/'

# Para onde redirecionar se um usuário não logado tentar acessar uma página protegida
LOGIN_URL = '/contas/login/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'



# ==========================================
# CONFIGURAÇÕES DO PAINEL ADMIN (JAZZMIN)
# ==========================================

JAZZMIN_SETTINGS = {
    # Títulos e Nomes
    "site_title": "LuxxCar Admin",
    "site_header": "LuxxCar",
    "site_brand": "LuxxCar Premium",
    "welcome_sign": "Bem-vindo ao Backoffice da LuxxCar",
    "copyright": "LuxxCar Motors Ltd",

    # Links do Menu Superior
    "topmenu_links": [
        {"name": "Início", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver o Site", "url": "/", "new_window": True},  # Abre o site real em outra aba
    ],

    # Ícones do Menu Lateral (FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "carros.Car": "fas fa-car-side",
        "carros.Brand": "fas fa-copyright",
        "carros.Sale": "fas fa-handshake",
        "carros.Notification": "fas fa-bell",
    },

    # Configurações Gerais
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["carros.Car", "carros.Sale"],  # Barra de pesquisa global
}

JAZZMIN_UI_TWEAKS = {
    # Ativa o Dark Mode ("darkly" é um tema bem escuro e elegante)
    "theme": "darkly",
    "dark_mode_theme": "darkly",

    # Personalização de Cores
    "button_classes": {
        "primary": "btn-warning",  # Deixa os botões principais amarelos/dourados
        "secondary": "btn-outline-light",
    },
    "actions_sticky_top": True,  # Trava a barra de ações no topo ao rolar a página
}
