# Generated by Django 6.0.2 on 2026-02-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Modelo')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('horsepower', models.IntegerField(verbose_name='Cavalos de Potência (HP)')),
                ('transmission', models.CharField(choices=[('Automatic', 'Automático'), ('Manual', 'Manual')], default='Automatic', max_length=20)),
                ('seats', models.IntegerField(verbose_name='Assentos')),
                ('zero_to_hundred', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='0-100 km/h (Segundos)')),
                ('drivetrain', models.CharField(default='AWD', max_length=50, verbose_name='Tração (Ex: AWD, RWD)')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Foto do Veículo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível para venda?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carros.brand', verbose_name='Marca')),
            ],
        ),
    ]
