# Generated by Django 6.0.2 on 2026-03-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tag')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatch', 'Hatchback'), ('Coupe', 'Coupé'), ('Convertible', 'Conversível'), ('Pickup', 'Picape'), ('Wagon', 'Perua/Wagon')], max_length=20, null=True, verbose_name='Carroceria'),
        ),
        migrations.AddField(
            model_name='car',
            name='segment',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxo'), ('Premium', 'Premium'), ('Sports', 'Esportivo Puro'), ('Standard', 'Padrão')], max_length=20, null=True, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cars', to='carros.tag', verbose_name='Proposta (Tags)'),
        ),
    ]
