# Generated by Django 6.0.2 on 2026-03-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_tag_car_body_type_car_segment_alter_car_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
    ]
