# Generated by Django 6.0.2 on 2026-03-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_remove_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('SALE', 'Venda/Reserva Realizada'), ('APPROVED', 'Venda Aprovada'), ('EDIT', 'Veículo Atualizado'), ('DELETE', 'Veículo Excluído')], default='SALE', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], default='AVAILABLE', max_length=20, verbose_name='Status do Veículo'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Comprador')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix (Desconto de 5%)'), ('CREDIT', 'Cartão de Crédito (Até 12x)'), ('FINANCE', 'Financiamento Bancário'), ('TED', 'Transferência TED/DOC')], max_length=20, verbose_name='Pagamento')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Fechado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente (Aguardando Pagamento)'), ('APPROVED', 'Aprovado (Pago)'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status da Venda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='carros.car', verbose_name='Carro')),
            ],
        ),
    ]
