# Generated by Django 6.0.2 on 2026-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_notification_remove_car_is_available_car_status_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Destino'),
        ),
    ]
