# Generated by Django 6.0.2 on 2026-03-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
